-- Généré automatiquement par scripts/export-ovh-seed.mjs

INSERT INTO cms_site_settings (
  id, site_name, baseline, mickael_name, marion_name, phone, email, main_city,
  covered_areas_json, facebook_url, instagram_url, iad_url, footer_text, main_cta_label, main_cta_url
) VALUES (
  1, 'Immobilier Auxois Morvan', 'Mickael Gury et Marion Roulier accompagnent les projets immobiliers en Auxois et dans le Morvan avec une approche sérieuse, locale et profondément humaine.', 'Mickael Gury', 'Marion Roulier',
  '+33 (0)6 00 00 00 00', 'contact@immobilier-auxois-morvan.fr', 'Arnay-le-Duc', '["Arnay-le-Duc","Pouilly-en-Auxois","Autun","Saulieu","Beaune","Dijon","Vitteaux","Semur-en-Auxois","Auxois","Morvan"]',
  'https://www.facebook.com/immobilier-auxois-morvan', 'https://www.instagram.com/immobilier.auxois.morvan', 'https://www.iadfrance.fr', 'Immobilier Auxois Morvan accompagne les projets immobiliers en Auxois et Morvan avec une approche locale, claire et humaine.',
  'Contactez-nous', '/contact'
) ON DUPLICATE KEY UPDATE
  site_name = VALUES(site_name),
  baseline = VALUES(baseline),
  mickael_name = VALUES(mickael_name),
  marion_name = VALUES(marion_name),
  phone = VALUES(phone),
  email = VALUES(email),
  main_city = VALUES(main_city),
  covered_areas_json = VALUES(covered_areas_json),
  facebook_url = VALUES(facebook_url),
  instagram_url = VALUES(instagram_url),
  iad_url = VALUES(iad_url),
  footer_text = VALUES(footer_text),
  main_cta_label = VALUES(main_cta_label),
  main_cta_url = VALUES(main_cta_url);

INSERT INTO cms_pages (
  page_type, page_key, slug, title, meta_description, is_indexable, h1, hero_title, hero_subtitle, hero_image, hero_image_alt,
  intro_html, sections_json, cta_title, cta_text, cta_button_label, cta_button_url, city, local_page_type, local_advantages_json, nearby_cities_json, status, published_at
) VALUES
('main', 'accueil', '/', 'Accueil', 'Conseillers immobiliers IAD en Auxois et Morvan. Mickael Gury et Marion Roulier vous accompagnent pour vendre, acheter ou estimer votre bien avec sérieux et proximité.', 1, 'Votre projet immobilier en Auxois et Morvan, accompagné avec sérieux et proximité', 'Votre projet immobilier en Auxois et Morvan, accompagné avec sérieux et proximité', 'Mickael Gury et Marion Roulier vous accompagnent pour vendre, acheter ou estimer votre bien autour d\'Arnay-le-Duc, Pouilly-en-Auxois, Autun, Beaune, Saulieu et Dijon.', '/uploads/auxois.jpg', 'Vue aérienne des paysages de l\'Auxois Morvan', '<p>Une présence de terrain, un accompagnement attentif et des conseils clairs pour avancer avec méthode à chaque étape de votre projet immobilier.</p>', '[{"eyebrow":"Réassurance","title":"Un accompagnement cadré, clair et humain","text":"<p>Nous travaillons avec des propriétaires, acquéreurs et commerçants qui veulent des repères fiables, une lecture honnête du marché local et un interlocuteur engagé jusqu\'à la signature.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Conseils précis sur le marché local","Disponibilité et suivi régulier","Coordination jusqu\'à l\'acte authentique"],"stats":[]},{"eyebrow":"Méthode","title":"Pourquoi nous confier votre projet","text":"<p>Notre approche repose sur l\'estimation juste, la qualité de présentation des biens, une diffusion ciblée et une vraie capacité d\'écoute pour défendre votre intérêt.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Analyse fine des secteurs et des micro-marchés","Stratégie de mise en vente ou de recherche adaptée","Accompagnement humain, sérieux et transparent"],"stats":[]},{"eyebrow":"Réseau","title":"L\'appui du réseau IAD","text":"<p>Nous combinons proximité locale et puissance de diffusion nationale pour donner plus de portée à votre projet, tout en gardant un interlocuteur unique.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":[],"stats":[{"label":"Réseau","value":"IAD France"},{"label":"Terrain couvert","value":"Auxois, Morvan et villes voisines"},{"label":"Suivi","value":"Personnalisé à chaque étape"}]}]', 'Parler de votre projet avec un conseiller local', '<p>Nous pouvons vous aider à estimer un bien, préparer une mise en vente, rechercher un achat ou cadrer un projet de cession de fonds de commerce.</p>', 'Demander une estimation', '/estimation', NULL, NULL, '[]', '[]', 'published', NOW()),
('main', 'acheter', '/acheter', 'Acheter un bien', 'Acheter un bien en Auxois ou dans le Morvan avec un conseiller immobilier local : connaissance du secteur, sélection de biens, accompagnement de visite et conseils de marché.', 1, 'Acheter un bien avec une lecture précise du marché local', 'Acheter dans l\'Auxois ou le Morvan avec des conseils utiles sur le terrain', 'Nous vous aidons à affiner votre recherche, à comprendre les spécificités du secteur et à avancer sereinement dans votre projet d\'acquisition.', '/uploads/maison.jpg', 'Maison de caractère disponible à l\'achat en Auxois Morvan', '<p>Un achat immobilier demande autant de méthode que d\'intuition. Notre rôle est de vous apporter un regard local, pragmatique et indépendant à chaque étape.</p>', '[{"eyebrow":"Écoute","title":"Une recherche cadrée selon votre projet réel","text":"<p>Nous prenons le temps de comprendre vos priorités, votre budget, votre rythme et vos critères pour cibler les biens pertinents dès le départ.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Clarification du cahier des charges","Priorisation des critères essentiels","Vision réaliste du marché disponible"],"stats":[]},{"eyebrow":"Terrain","title":"Une vraie connaissance des villages, bassins de vie et axes","text":"<p>Nous vous aidons à comparer les secteurs, à mesurer les temps de trajet, à identifier les services de proximité et à comprendre les dynamiques locales.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Lecture des micro-secteurs","Conseils sur le potentiel du bien","Repères concrets pour arbitrer"],"stats":[]},{"eyebrow":"Accompagnement","title":"Un suivi présent jusqu\'à la concrétisation","text":"<p>Nous restons disponibles pour les visites, les questions de positionnement, la lecture des documents et le suivi du dossier jusqu\'à l\'acquisition.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Préparation des visites","Aide à la décision et à l\'offre","Coordination des étapes du dossier"],"stats":[]}]', 'Échanger sur votre recherche immobilière', '<p>Que vous cherchiez une résidence principale, secondaire ou un investissement, nous pouvons vous orienter vers les secteurs les plus cohérents avec votre projet.</p>', 'Nous contacter', '/contact', NULL, NULL, '[]', '[]', 'published', NOW()),
('main', 'contact', '/contact', 'Contact', 'Contactez Mickael Gury et Marion Roulier, conseillers immobiliers IAD en Auxois et Morvan, pour vendre, acheter, estimer un bien ou parler de votre secteur.', 1, 'Nous contacter pour parler de votre projet immobilier', 'Un premier échange simple, direct et utile', 'Que vous souhaitiez vendre, acheter, faire estimer un bien ou préparer une cession de fonds de commerce, nous sommes disponibles pour vous répondre.', '/uploads/photo-IAD-fond.jpg', 'Maison en pierre représentative du secteur Auxois Morvan', '<p>Nous privilégions les échanges clairs et concrets pour comprendre votre projet, répondre à vos questions et vous proposer la meilleure suite.</p>', '[{"eyebrow":"Présentation","title":"Mickael Gury et Marion Roulier","text":"<p>Deux conseillers immobiliers IAD impliqués sur leur secteur, disponibles pour accompagner des projets de vente, d\'achat, d\'estimation et de transmission avec sérieux et proximité.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Approche humaine et professionnelle","Connaissance du terrain et des villages","Suivi personnalisé"],"stats":[]},{"eyebrow":"Coordonnées","title":"Des coordonnées simples et des créneaux souples","text":"<p>Nous pouvons convenir d\'un rendez-vous, échanger au téléphone ou répondre par email selon l\'urgence et la nature de votre demande.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Téléphone placeholder modifiable depuis les réglages","Email placeholder modifiable depuis les réglages","Secteur couvert rappelé sur la page"],"stats":[]},{"eyebrow":"Estimation","title":"Une demande d\'estimation peut être préparée dès le premier contact","text":"<p>Donnez-nous quelques informations sur le bien, sa localisation et votre calendrier pour engager une première lecture de votre projet.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":[],"stats":[]}]', 'Demander une estimation ou un rendez-vous', '<p>Utilisez le formulaire ci-dessous ou contactez-nous directement. Le site est prêt pour évoluer ensuite vers un CMS GitHub sans backend ni base de données.</p>', 'Faire estimer mon bien', '/estimation', NULL, NULL, '[]', '[]', 'published', NOW()),
('main', 'estimation', '/estimation', 'Estimation immobilière', 'Demander une estimation immobilière en Auxois ou dans le Morvan. Avis de valeur, analyse du marché local et accompagnement par Mickael Gury et Marion Roulier.', 1, 'Une estimation immobilière sérieuse, argumentée et utile à la décision', 'Estimer votre bien avec une lecture réaliste du marché local', 'Nous vous remettons un avis de valeur construit à partir des références du secteur, des caractéristiques du bien et de l\'objectif de votre projet.', '/uploads/estimer.jpg', 'Conseiller immobilier préparant une estimation de bien', '<p>Une estimation fiable ne se limite pas à une fourchette. Elle permet de fixer une stratégie, d\'anticiper les délais et de sécuriser les prochaines étapes de votre projet.</p>', '[{"eyebrow":"Marché","title":"Une analyse du marché local fondée sur des repères concrets","text":"<p>Nous comparons votre bien aux ventes et offres pertinentes du secteur, avec un regard attentif sur l\'environnement, la demande et les critères spécifiques.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Références locales récentes","Analyse de la demande et de la concurrence","Lecture du positionnement du bien"],"stats":[]},{"eyebrow":"Spécificités","title":"Les caractéristiques du bien sont examinées en détail","text":"<p>Surface, état, prestations, potentiel, annexes, travaux, vue, emplacement ou usage influencent fortement la valeur et doivent être intégrés avec nuance.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Analyse des points forts et points de vigilance","Ajustements selon les usages et le secteur","Avis de valeur cohérent avec votre projet"],"stats":[]},{"eyebrow":"Décision","title":"Une estimation pensée pour déclencher la bonne action","text":"<p>L\'objectif est de vous donner une base sérieuse pour vendre, arbitrer un projet patrimonial ou préparer une cession dans de bonnes conditions.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Mise en vente","Arbitrage patrimonial","Préparation d\'une succession ou d\'un projet de vie"],"stats":[]}]', 'Demander un avis de valeur', '<p>Nous pouvons intervenir autour d\'Arnay-le-Duc, Pouilly-en-Auxois, Autun, Saulieu, Beaune, Dijon et dans les environs pour une estimation claire et argumentée.</p>', 'Demander une estimation', '/contact', NULL, NULL, '[]', '[]', 'published', NOW()),
('main', 'fonds-de-commerce', '/fonds', 'Fonds de commerce', 'Accompagnement à la vente de fonds de commerce en Auxois, Morvan, Beaune, Dijon et environs : estimation, dossier acquéreur, diffusion et qualification des repreneurs.', 1, 'Vendre un fonds de commerce avec une approche structurée et confidentielle', 'Un accompagnement dédié aux commerçants et aux projets de transmission', 'Nous vous aidons à préparer la cession, à construire un dossier clair et à qualifier les repreneurs pour conduire la vente dans de bonnes conditions.', '/uploads/our-services-3.jpg', 'Façade de commerce prêt à être transmis', '<p>La transmission d\'un fonds de commerce demande une lecture à la fois immobilière, économique et humaine. Notre rôle est d\'apporter de la méthode et de la discrétion.</p>', '[{"eyebrow":"Valorisation","title":"Une estimation cohérente avec l\'activité et son environnement","text":"<p>Nous croisons les éléments liés au chiffre d\'affaires, à l\'emplacement, au bail, au potentiel de reprise et au contexte local pour définir une base crédible.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Lecture du positionnement commercial","Analyse de l\'environnement et de la zone de chalandise","Avis de valeur argumenté"],"stats":[]},{"eyebrow":"Dossier","title":"Un dossier acquéreur préparé pour faciliter les échanges","text":"<p>Nous structurons les informations essentielles afin de présenter l\'activité de manière claire, sérieuse et exploitable par les candidats repreneurs.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Présentation synthétique de l\'activité","Mise en avant des forces du commerce","Informations utiles au cadrage des visites"],"stats":[]},{"eyebrow":"Diffusion","title":"Une diffusion large avec qualification des repreneurs","text":"<p>Nous ciblons la communication, pilotons les prises de contact et filtrons les profils pour sécuriser le temps du cédant et la qualité des échanges.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Diffusion adaptée au dossier","Qualification des candidats","Accompagnement jusqu\'à la vente"],"stats":[]}]', 'Échanger sur une cession de fonds de commerce', '<p>Nous pouvons vous aider à cadrer une transmission, à préparer les supports de présentation et à qualifier les acquéreurs potentiels.</p>', 'Nous contacter', '/contact', NULL, NULL, '[]', '[]', 'published', NOW()),
('main', 'secteur', '/secteur', 'Secteur d\'intervention', 'Découvrez les secteurs couverts par Mickael Gury et Marion Roulier en Auxois, Morvan, Arnay-le-Duc, Pouilly-en-Auxois, Autun, Saulieu, Beaune, Dijon, Vitteaux et Semur-en-Auxois.', 1, 'Un accompagnement immobilier ancré dans l\'Auxois, le Morvan et leurs villes de proximité', 'Notre secteur d\'intervention', 'Nous accompagnons des projets immobiliers dans les villages, petites villes et pôles d\'activité de l\'Auxois, du Morvan et des environs.', '/uploads/auxois.jpg', 'Paysages vallonnés entre Auxois et Morvan', '<p>La valeur d\'un conseil immobilier local tient à la connaissance fine des rythmes de marché, des profils d\'acquéreurs et des spécificités de chaque secteur.</p>', '[{"eyebrow":"Villes clés","title":"Des secteurs suivis régulièrement","text":"<p>Nous intervenons notamment à Arnay-le-Duc, Pouilly-en-Auxois, Autun, Saulieu, Beaune, Dijon, Vitteaux et Semur-en-Auxois, ainsi que dans les villages environnants.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Arnay-le-Duc","Pouilly-en-Auxois","Autun","Saulieu","Beaune","Dijon","Vitteaux","Semur-en-Auxois"],"stats":[]},{"eyebrow":"Territoire","title":"Auxois et Morvan : deux territoires aux réalités complémentaires","text":"<p>Nous adaptons notre lecture du marché selon les attentes des vendeurs et acquéreurs, la typologie des biens et les dynamiques propres à chaque bassin de vie.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Résidences principales","Maisons de village ou de campagne","Biens de caractère et projets de vie"],"stats":[]},{"eyebrow":"SEO local","title":"Des pages locales dédiées pour mieux informer les propriétaires","text":"<p>Le site peut accueillir des pages ciblées par ville ou par intention pour répondre plus précisément aux recherches locales et faciliter la prise de contact.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":[],"stats":[]}]', 'Voir si nous intervenons sur votre commune', '<p>Contactez-nous pour échanger sur votre bien, votre calendrier et les spécificités de votre secteur, même si votre commune n\'apparaît pas encore sur le site.</p>', 'Nous parler de votre secteur', '/contact', NULL, NULL, '[]', '[]', 'published', NOW()),
('main', 'vendre', '/vendre', 'Vendre votre bien', 'Vendre un bien en Auxois ou dans le Morvan avec Mickael Gury et Marion Roulier : estimation juste, stratégie de prix, valorisation, diffusion et négociation.', 1, 'Vendre votre bien avec une stratégie claire et un accompagnement rigoureux', 'Vendre votre bien avec méthode, visibilité et exigence', 'De l\'avis de valeur à la signature, nous structurons chaque étape pour défendre votre prix, votre calendrier et la qualité du dossier acquéreur.', '/uploads/maison-Maconge-20.jpg', 'Maison familiale en pierre en Auxois Morvan', '<p>Une vente réussie repose sur la justesse du positionnement, la qualité de présentation du bien et la capacité à piloter efficacement les échanges jusqu\'à l\'acte.</p>', '[{"eyebrow":"Estimation","title":"Une estimation juste pour lancer la vente sur de bonnes bases","text":"<p>Nous analysons votre bien, son environnement, les références récentes et les attentes du marché local pour définir un prix cohérent et crédible.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Avis de valeur argumenté","Analyse du secteur et de la demande","Positionnement adapté au calendrier du vendeur"],"stats":[]},{"eyebrow":"Valorisation","title":"Un plan de présentation pensé pour convaincre","text":"<p>Nous mettons en avant les atouts du bien, sa lecture par les acquéreurs et son potentiel grâce à une présentation soignée et une communication précise.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Sélection des arguments clés","Préparation du dossier de vente","Diffusion qualitative et cohérente"],"stats":[]},{"eyebrow":"Négociation","title":"Un suivi constant jusqu\'à la signature","text":"<p>Nous filtrons les contacts, organisons les visites, qualifions les projets et vous accompagnons dans les négociations comme dans les démarches finales.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Qualification des acquéreurs","Pilotage des offres et contre-propositions","Coordination avec les interlocuteurs du dossier"],"stats":[]}]', 'Préparer une vente dans de bonnes conditions', '<p>Si vous envisagez de vendre à Arnay-le-Duc, Pouilly-en-Auxois, Autun, Saulieu, Beaune ou Dijon, nous pouvons vous aider à cadrer la stratégie dès le départ.</p>', 'Obtenir une estimation', '/estimation', NULL, NULL, '[]', '[]', 'published', NOW()),
('local', NULL, 'estimation-immobiliere-arnay-le-duc', 'Estimation immobilière à Arnay-le-Duc', 'Demandez une estimation immobilière à Arnay-le-Duc avec un conseiller local. Avis de valeur, analyse du marché et accompagnement sur votre projet de vente.', 1, 'Estimation immobilière à Arnay-le-Duc', 'Faire estimer son bien à Arnay-le-Duc avec un regard local', 'Nous vous aidons à positionner votre bien à Arnay-le-Duc et dans les communes voisines avec une estimation argumentée et cohérente avec le marché local.', '/uploads/arnay.jpg', 'Vue du centre d\'Arnay-le-Duc', '<p>Entre centre-bourg, maisons anciennes, biens familiaux et projets de vie plus ruraux, une estimation à Arnay-le-Duc doit tenir compte de la demande locale et du cadre de vie recherché.</p>', '[{"eyebrow":"Marché local","title":"Un avis de valeur adapté au marché d\'Arnay-le-Duc","text":"<p>Nous observons les références du secteur, le niveau de demande, l\'état du bien et sa situation pour établir une estimation utile à la décision.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Références comparables du secteur","Lecture du positionnement du bien","Analyse de l\'attractivité locale"],"stats":[]},{"eyebrow":"Projet vendeur","title":"Une estimation pensée pour préparer la vente","text":"<p>L\'objectif n\'est pas seulement de donner un chiffre, mais de vous permettre de décider du bon timing, d\'un prix réaliste et d\'une stratégie de mise en marché.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Calendrier de vente","Potentiel de valorisation","Arguments de commercialisation"],"stats":[]},{"eyebrow":"Accompagnement","title":"Un interlocuteur présent à chaque étape","text":"<p>Si vous poursuivez la mise en vente, nous pouvons également vous accompagner sur la présentation, la diffusion et le suivi du dossier.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":[],"stats":[]}]', 'Demander une estimation à Arnay-le-Duc', '<p>Nous pouvons planifier un premier échange pour comprendre votre bien et préparer un avis de valeur adapté à votre projet.</p>', 'Nous contacter', '/contact', 'Arnay-le-Duc', 'estimation-immobiliere', '["Connaissance des villages autour d\'Arnay-le-Duc","Lecture des profils acquéreurs recherchant un cadre de vie local","Accompagnement de proximité avec un interlocuteur unique"]', '["Pouilly-en-Auxois","Saulieu","Beaune"]', 'published', NOW()),
('local', NULL, 'estimation-immobiliere-pouilly-en-auxois', 'Estimation immobilière à Pouilly-en-Auxois', 'Estimation immobilière à Pouilly-en-Auxois : avis de valeur, analyse du marché local et accompagnement pour vendre votre bien avec Mickael Gury et Marion Roulier.', 1, 'Estimation immobilière à Pouilly-en-Auxois', 'Estimer un bien à Pouilly-en-Auxois avec méthode', 'Nous analysons votre bien et les dynamiques du secteur de Pouilly-en-Auxois pour vous donner une base crédible avant une vente ou un arbitrage patrimonial.', '/uploads/pouilly.jpg', 'Vue aérienne de Pouilly-en-Auxois', '<p>Entre axe de passage, attractivité résidentielle et diversité de biens, Pouilly-en-Auxois demande une lecture fine du marché et des profils acquéreurs.</p>', '[{"eyebrow":"Références","title":"Une estimation appuyée sur des repères de marché utiles","text":"<p>Nous croisons les ventes comparables, la qualité du bien, sa localisation et les attentes des acheteurs pour ajuster l\'avis de valeur.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Biens comparables récents","Environnement et accessibilité","Caractéristiques différenciantes"],"stats":[]},{"eyebrow":"Stratégie","title":"Un avis de valeur qui prépare la suite","text":"<p>Une bonne estimation doit vous aider à anticiper les délais, cadrer votre prix et décider des améliorations ou arbitrages à effectuer avant la vente.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Prix de mise en vente","Points de valorisation du bien","Niveau de tension du marché"],"stats":[]},{"eyebrow":"Suivi","title":"Un accompagnement local si vous mettez le bien en vente","text":"<p>Nous pouvons ensuite structurer la présentation du bien, piloter la diffusion et suivre les acquéreurs intéressés.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":[],"stats":[]}]', 'Demander une estimation à Pouilly-en-Auxois', '<p>Parlons de votre bien et de votre calendrier pour préparer un avis de valeur clair, cohérent et exploitable.</p>', 'Faire estimer mon bien', '/contact', 'Pouilly-en-Auxois', 'estimation-immobiliere', '["Connaissance du bassin de vie autour de Pouilly-en-Auxois","Lecture des atouts de mobilité et de centralité","Accompagnement sérieux jusqu\'à la signature"]', '["Arnay-le-Duc","Vitteaux","Dijon"]', 'published', NOW()),
('local', NULL, 'vendre-maison-autun', 'Vendre sa maison à Autun', 'Vendre sa maison à Autun avec l\'appui d\'un conseiller immobilier local : estimation, stratégie de prix, valorisation, diffusion et négociation.', 1, 'Vendre sa maison à Autun', 'Préparer la vente de votre maison à Autun avec un accompagnement structuré', 'Nous vous aidons à estimer, positionner et présenter votre bien pour toucher les bons acquéreurs à Autun et dans son bassin de vie.', '/uploads/autun.jpg', 'Vue de la ville d\'Autun', '<p>À Autun, la lecture du marché dépend fortement du quartier, du type de maison, de l\'état du bien et du projet des acquéreurs. Une vente efficace commence par cette analyse.</p>', '[{"eyebrow":"Prix","title":"Définir une stratégie de prix solide dès le départ","text":"<p>Nous étudions les références locales, la qualité du bien et le rythme du marché pour vous aider à lancer la vente dans de bonnes conditions.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Avis de valeur détaillé","Positionnement cohérent avec la demande","Analyse du délai de vente probable"],"stats":[]},{"eyebrow":"Présentation","title":"Valoriser la maison pour convaincre dès les premières visites","text":"<p>Nous travaillons les arguments de présentation, la sélection des visuels et la hiérarchie des informations utiles pour les acquéreurs.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":["Mise en avant des points forts","Préparation du dossier de présentation","Discours commercial cohérent"],"stats":[]},{"eyebrow":"Négociation","title":"Conduire la vente avec rigueur jusqu\'à la signature","text":"<p>Nous qualifions les candidats, gérons les échanges et vous accompagnons dans les arbitrages pour sécuriser la vente.</p>","image":"","imageAlt":"","buttonLabel":"","buttonUrl":"","items":[],"stats":[]}]', 'Préparer la vente de votre maison à Autun', '<p>Nous pouvons vous aider à cadrer le prix, organiser la commercialisation et piloter la vente jusqu\'à la signature.</p>', 'Demander une estimation', '/estimation', 'Autun', 'vendre-maison', '["Bonne connaissance du marché autunois et de ses alentours","Accompagnement de proximité pour les visites et les échanges","Suivi rigoureux jusqu\'à la conclusion de la vente"]', '["Saulieu","Beaune","Arnay-le-Duc"]', 'published', NOW())
ON DUPLICATE KEY UPDATE
  slug = VALUES(slug),
  title = VALUES(title),
  meta_description = VALUES(meta_description),
  is_indexable = VALUES(is_indexable),
  h1 = VALUES(h1),
  hero_title = VALUES(hero_title),
  hero_subtitle = VALUES(hero_subtitle),
  hero_image = VALUES(hero_image),
  hero_image_alt = VALUES(hero_image_alt),
  intro_html = VALUES(intro_html),
  sections_json = VALUES(sections_json),
  cta_title = VALUES(cta_title),
  cta_text = VALUES(cta_text),
  cta_button_label = VALUES(cta_button_label),
  cta_button_url = VALUES(cta_button_url),
  city = VALUES(city),
  local_page_type = VALUES(local_page_type),
  local_advantages_json = VALUES(local_advantages_json),
  nearby_cities_json = VALUES(nearby_cities_json),
  status = VALUES(status),
  published_at = VALUES(published_at);
