CREATE TABLE IF NOT EXISTS cms_admin_users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(190) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'admin',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_cms_admin_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cms_pages (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  page_type ENUM('main', 'local') NOT NULL,
  page_key VARCHAR(100) DEFAULT NULL,
  slug VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  meta_description TEXT NOT NULL,
  is_indexable TINYINT(1) NOT NULL DEFAULT 1,
  h1 VARCHAR(255) NOT NULL,
  hero_title VARCHAR(255) NOT NULL,
  hero_subtitle LONGTEXT NOT NULL,
  hero_image VARCHAR(255) DEFAULT NULL,
  hero_image_alt VARCHAR(255) DEFAULT NULL,
  intro_html LONGTEXT NOT NULL,
  sections_json LONGTEXT NOT NULL,
  cta_title VARCHAR(255) NOT NULL,
  cta_text LONGTEXT NOT NULL,
  cta_button_label VARCHAR(150) NOT NULL,
  cta_button_url VARCHAR(255) NOT NULL,
  city VARCHAR(150) DEFAULT NULL,
  local_page_type VARCHAR(150) DEFAULT NULL,
  local_advantages_json LONGTEXT DEFAULT NULL,
  nearby_cities_json LONGTEXT DEFAULT NULL,
  seo_intent VARCHAR(80) DEFAULT NULL,
  seo_status VARCHAR(40) NOT NULL DEFAULT 'draft',
  seo_focus_keyword VARCHAR(190) DEFAULT NULL,
  seo_secondary_keywords LONGTEXT DEFAULT NULL,
  seo_template VARCHAR(80) DEFAULT NULL,
  seo_notes LONGTEXT DEFAULT NULL,
  seo_faq_json LONGTEXT DEFAULT NULL,
  seo_internal_links_json LONGTEXT DEFAULT NULL,
  seo_is_primary TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('draft', 'published') NOT NULL DEFAULT 'draft',
  published_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_cms_pages_slug (slug),
  UNIQUE KEY uniq_cms_pages_page_key (page_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cms_blog_posts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  excerpt TEXT NOT NULL,
  category VARCHAR(150) DEFAULT NULL,
  featured_image VARCHAR(255) DEFAULT NULL,
  featured_image_alt VARCHAR(255) DEFAULT NULL,
  content_html LONGTEXT NOT NULL,
  meta_title VARCHAR(255) DEFAULT NULL,
  meta_description TEXT DEFAULT NULL,
  is_indexable TINYINT(1) NOT NULL DEFAULT 1,
  status ENUM('draft', 'published') NOT NULL DEFAULT 'draft',
  published_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_cms_blog_posts_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cms_media (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  original_name VARCHAR(255) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  public_url VARCHAR(255) NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  size_bytes INT UNSIGNED NOT NULL,
  alt_text VARCHAR(255) DEFAULT NULL,
  title VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_cms_media_file_name (file_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cms_site_settings (
  id TINYINT UNSIGNED NOT NULL DEFAULT 1,
  site_name VARCHAR(255) NOT NULL,
  baseline LONGTEXT NOT NULL,
  mickael_name VARCHAR(150) NOT NULL,
  marion_name VARCHAR(150) NOT NULL,
  mickael_photo VARCHAR(255) DEFAULT NULL,
  marion_photo VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(50) NOT NULL,
  email VARCHAR(190) NOT NULL,
  main_city VARCHAR(150) NOT NULL,
  covered_areas_json LONGTEXT NOT NULL,
  facebook_url VARCHAR(255) DEFAULT NULL,
  instagram_url VARCHAR(255) DEFAULT NULL,
  iad_url VARCHAR(255) DEFAULT NULL,
  footer_text LONGTEXT NOT NULL,
  main_cta_label VARCHAR(150) NOT NULL,
  main_cta_url VARCHAR(255) NOT NULL,
  blog_enabled TINYINT(1) NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cms_contact_requests (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(190) NOT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  subject VARCHAR(255) DEFAULT NULL,
  message TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cms_estimation_requests (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  request_type VARCHAR(50) NOT NULL DEFAULT 'estimation',
  property_type VARCHAR(100) NOT NULL,
  room_count VARCHAR(100) NOT NULL,
  property_condition VARCHAR(100) NOT NULL,
  living_surface VARCHAR(100) NOT NULL,
  land_surface VARCHAR(100) NOT NULL,
  occupancy_intent VARCHAR(150) DEFAULT NULL,
  commune VARCHAR(150) NOT NULL,
  postal_code VARCHAR(20) DEFAULT NULL,
  address_details TEXT NOT NULL,
  goal VARCHAR(150) NOT NULL,
  owner_situation VARCHAR(150) DEFAULT NULL,
  project_timeline VARCHAR(100) NOT NULL,
  first_name VARCHAR(150) NOT NULL,
  last_name VARCHAR(150) NOT NULL,
  email VARCHAR(190) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  contact_consent TINYINT(1) NOT NULL DEFAULT 0,
  outside_area TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(50) NOT NULL DEFAULT 'new',
  internal_notes LONGTEXT DEFAULT NULL,
  source VARCHAR(150) NOT NULL DEFAULT 'formulaire estimation en ligne',
  utm_source VARCHAR(190) DEFAULT NULL,
  utm_campaign VARCHAR(190) DEFAULT NULL,
  utm_content VARCHAR(190) DEFAULT NULL,
  utm_medium VARCHAR(190) DEFAULT NULL,
  origin_page VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_cms_estimation_requests_type (request_type),
  KEY idx_cms_estimation_requests_status (status),
  KEY idx_cms_estimation_requests_commune (commune),
  KEY idx_cms_estimation_requests_created_at (created_at),
  KEY idx_cms_estimation_requests_utm_campaign (utm_campaign)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cms_estimation_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_name VARCHAR(100) NOT NULL,
  visitor_id VARCHAR(80) NOT NULL,
  session_id VARCHAR(80) DEFAULT NULL,
  step_number TINYINT UNSIGNED DEFAULT NULL,
  step_field VARCHAR(100) DEFAULT NULL,
  choice_value VARCHAR(180) DEFAULT NULL,
  page_url VARCHAR(255) DEFAULT NULL,
  referrer VARCHAR(255) DEFAULT NULL,
  utm_source VARCHAR(190) DEFAULT NULL,
  utm_medium VARCHAR(190) DEFAULT NULL,
  utm_campaign VARCHAR(190) DEFAULT NULL,
  utm_content VARCHAR(190) DEFAULT NULL,
  ip_hash CHAR(64) DEFAULT NULL,
  user_agent_hash CHAR(64) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_cms_estimation_events_created_at (created_at),
  KEY idx_cms_estimation_events_event_name (event_name),
  KEY idx_cms_estimation_events_visitor (visitor_id),
  KEY idx_cms_estimation_events_step (step_number),
  KEY idx_cms_estimation_events_utm_campaign (utm_campaign)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cms_seo_keywords (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  keyword VARCHAR(255) NOT NULL,
  city VARCHAR(150) DEFAULT NULL,
  intent VARCHAR(80) NOT NULL DEFAULT 'local',
  target_url VARCHAR(255) DEFAULT NULL,
  target_page_id INT UNSIGNED DEFAULT NULL,
  priority TINYINT UNSIGNED NOT NULL DEFAULT 2,
  status ENUM('active','paused','to-create','to-optimize') NOT NULL DEFAULT 'active',
  action_status VARCHAR(60) DEFAULT NULL,
  notes LONGTEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_cms_seo_keywords_keyword (keyword),
  KEY idx_cms_seo_keywords_city (city),
  KEY idx_cms_seo_keywords_target_page (target_page_id),
  KEY idx_cms_seo_keywords_action_status (action_status),
  KEY idx_cms_seo_keywords_status (status),
  KEY idx_cms_seo_keywords_priority (priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cms_seo_measurements (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  keyword_id INT UNSIGNED NOT NULL,
  source ENUM('manual','csv','search_console') NOT NULL DEFAULT 'manual',
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  clicks INT UNSIGNED NOT NULL DEFAULT 0,
  impressions INT UNSIGNED NOT NULL DEFAULT 0,
  ctr DECIMAL(8,4) NOT NULL DEFAULT 0,
  position DECIMAL(8,2) DEFAULT NULL,
  best_page VARCHAR(255) DEFAULT NULL,
  raw_json LONGTEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_cms_seo_measurements_keyword_date (keyword_id, period_end),
  KEY idx_cms_seo_measurements_source (source),
  CONSTRAINT fk_cms_seo_measurements_keyword
    FOREIGN KEY (keyword_id) REFERENCES cms_seo_keywords(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cms_seo_oauth_tokens (
  provider VARCHAR(60) NOT NULL,
  access_token LONGTEXT DEFAULT NULL,
  refresh_token LONGTEXT DEFAULT NULL,
  token_type VARCHAR(40) DEFAULT NULL,
  scope LONGTEXT DEFAULT NULL,
  expires_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (provider)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cms_seo_ai_analyses (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  analysis_type VARCHAR(60) NOT NULL DEFAULT 'overview',
  model VARCHAR(80) DEFAULT NULL,
  result_json LONGTEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_cms_seo_ai_analyses_type_date (analysis_type, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;